[package]
name = "rooney"
version = "0.1.0"
edition = "2021"

[dependencies]
# GUI & Wayland Windowing
libcosmic = { git = "https://github.com/pop-os/libcosmic", rev = "d4d71fd53e5ed6bd3a430089114dffa2da3cd498" }
cosmic-text = "0.12"

# Text Buffer & Core
ropey = "1.6"

# Parsing & Syntax
tree-sitter = "0.24"
tree-sitter-rust = "0.23"
tree-sitter-python = "0.23"
tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-c = "0.23"
tree-sitter-cpp = "0.23"
tree-sitter-bash = "0.23"
tree-sitter-fish = "3.6"
tree-sitter-json = "0.24"
tree-sitter-toml-ng = "0.7"
tree-sitter-yaml = "0.7"
pulldown-cmark = "0.12"

# Image Processing
image = "0.25"

# Local AI Integration (Ollama FIM)
tokio = { version = "1.40", features = ["rt-multi-thread", "time", "net", "macros"] }
reqwest = { version = "0.12", features = ["stream", "json"] }
futures-util = "0.3"
futures-channel = "0.3"

# Config & Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
directories = "5.0"
walkdir = "2.5"
unicode-width = "0.2"
rfd = "0.17.2"
